# Codecov Configuration
# This file configures code coverage reporting and test analytics for the ETL pipeline project

# Coverage settings
coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: true
    patch:
      default:
        target: auto
        threshold: 1%
        informational: true

  # Precision for coverage percentages
  precision: 2
  round: down
  range: "70...100"

# Comment settings - appears on pull requests
comment:
  layout: "header, diff, flags, components, tree"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

# Annotations - show line-by-line coverage on PR diffs
github_checks:
  annotations: true
  annotations_overall_threshold: 0

# Flag configuration for separating test types
flags:
  unittests:
    carryforward: true
    paths:
      - extract/src/main/java/
      - transform/src/main/java/
      - load/src/main/java/
      - runner/src/main/java/

# Ignore paths that shouldn't be counted in coverage
ignore:
  - "**/test/**"
  - "**/build/**"
  - "**/*.gradle"
  - "gradle/**"
