# Codecov Configuration
# This file configures code coverage reporting and test analytics for the ETL pipeline project

# Coverage settings
coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: false
        if_ci_failed: error
    patch:
      default:
        target: auto
        threshold: 1%
        informational: false
        if_ci_failed: error

  # Precision for coverage percentages
  precision: 2
  round: down
  range: "70...100"

# Comment settings - appears on pull requests
comment:
  layout: "header, diff, flags, components, tree"
  behavior: default
  require_changes: false
  require_base: true
  require_head: true
  template: |
    ## 📊 Code Coverage Report
    {{ if .Coverage }}
    - **Project Coverage**: {{ .Coverage }}%
    - **Patch Coverage**: {{ .PatchCoverage }}%
    {{ end }}
    {{ if .Files }}
    ### 📁 Files Changed
    {{ range .Files }}
    - **{{ .File }}**: {{ .Coverage }}% ({{ .LinesCovered }}/{{ .LinesTotal }} lines)
    {{ end }}
    {{ end }}

# Annotations - show line-by-line coverage on PR diffs
github_checks:
  annotations: true
  annotations_overall_threshold: 0  # Show all uncovered lines, don't require 100%
  # Enable separate Codecov check runs
  enabled: true
  # Fail checks if coverage drops
  fail_ci_if_error: true

# Flag configuration for separating test types
flags:
  unittests:
    carryforward: false
    paths:
      - extract/src/main/java/
      - transform/src/main/java/
      - load/src/main/java/
      - runner/src/main/java/
    # Strict coverage requirements for each flag
    target: auto
    threshold: 0%
    if_ci_failed: error

# Ignore paths that shouldn't be counted in coverage
ignore:
  - "**/test/**"
  - "**/build/**"
  - "**/*.gradle"
  - "gradle/**"

# Ensure we process all files
codecov:
  # Require coverage for all files, not just modified ones
  require_base: true
  require_head: true
